### ISSUE TITLE
Typo in acme 

### ISSUE THREAD

**Issue by BaccanoMob** [wollomatic/traefik-hardened#5]
Its just a small typo. The second code block in acme folder should be

```
touch acmedns.json
sudo chown 2000:2000 acmedns.json
sudo chmod 600 acmedns.json
```

according to your traefik.yaml file since dns refers to acmedns.json while tls refers to acme.json file.

**Comment by wollomatic** [comment]
Hi @BaccanoMob,

thanks for the info. I just fixed the file.

Best regards,
Wolfgang
